image: shivam086r/pipeline-image:latest

pipelines:
  custom:
    build-and-deploy:
      - step:
          name: Build and Deploy to S3
          caches:
            - maven
          script:
            #  Installed packages 
            - mvn -v
            - aws --version
            - java -version

            # Configure AWS CLI
            - echo "Configuring AWS CLI"
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - aws configure set region $AWS_DEFAULT_REGION

            # Build the application
            - echo "Building the application"
            - mvn clean package -DskipTests # Build the JAR file

            # Upload JAR to S3
            - echo "Uploading JAR to S3"
            - aws s3 cp target/paybyte-user-service-0.0.1-SNAPSHOT.jar s3://testeeeiing-artifacts/user-service/
          artifacts:
            - target/paybyte-user-service-0.0.1-SNAPSHOT.jar
