# Use Amazon Linux 2023 as the base image
FROM amazonlinux:2023

# Set environment variables for non-interactive installations
ENV LANG C.UTF-8

# Update the system and install required tools
RUN echo "Installing required tools" && \
    yum update -y && \
    yum install -y tar gzip unzip jq && \
    # Install Packer
    yum install -y yum-utils && \
    yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo && \
    yum -y install packer && \
    packer --version && \
    # Install AWS CLI
    echo "Installing AWS CLI" && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws && \
    echo "AWS CLI installed successfully" && \
    # Install Git
    yum install git -y && \
    # Print versions of Java, Maven, and AWS CLI
    git --version && \
    aws --version && \
    packer -version

# Set the default command to run
CMD ["/bin/bash"]
